## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np
import random

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Создать вектор размера 10, заполненный единицами

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Создать вектор размера 10, заполненный числом 2.5

In [5]:
np.array([2.5]*10)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [6]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

Развернуть вектор (первый становится последним)

In [7]:
reversed_arr = a[::-1]
reversed_arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [9]:
arr = np.array([1,2,0,0,4,0])
np.where(arr!=0)

(array([0, 1, 4]),)

Создать 3x3 единичную матрицу

In [10]:
np.ones(9).reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Создать массив 3x3x3 со случайными значениями

In [11]:
np.random.rand(3,3,3)

array([[[0.66437126, 0.94218271, 0.81217452],
        [0.96494072, 0.16994097, 0.250265  ],
        [0.92620173, 0.04838901, 0.12678178]],

       [[0.69970608, 0.46926882, 0.52187934],
        [0.93530227, 0.76691218, 0.8517107 ],
        [0.86982613, 0.67922922, 0.81302996]],

       [[0.45126316, 0.38607382, 0.71566874],
        [0.16787801, 0.75761416, 0.01145143],
        [0.12005077, 0.65822676, 0.59740763]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [12]:
np.random.rand(1,30).mean()

0.5496197997836536

Перемножить матрицы 5x3 и 3x2

In [13]:
a1 = np.random.rand(5,3)
a2 = np.random.rand(3,2)
a1.dot(a2)

array([[0.93781263, 1.1236264 ],
       [1.13558875, 1.08798712],
       [0.83078387, 0.89962004],
       [0.85048312, 0.99448238],
       [1.0000625 , 0.96411576]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [14]:
a = np.linspace(0.1, 1,num = 10, endpoint = False)
a

array([0.1 , 0.19, 0.28, 0.37, 0.46, 0.55, 0.64, 0.73, 0.82, 0.91])

Заменить максимальный элемент на ноль

In [15]:
a[a.argmax()] = 0 
a

array([0.1 , 0.19, 0.28, 0.37, 0.46, 0.55, 0.64, 0.73, 0.82, 0.  ])

Преобразовать массив из float в int

In [16]:
b = a.astype(int)
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [26]:
import scipy.spatial
a = np.random.random((10,2))
scipy.spatial.distance.cdist(a,a)

array([[0.        , 0.43927332, 0.53882322, 0.70303005, 0.54332408,
        0.25424385, 0.21522677, 1.06313451, 0.34283371, 0.70592601],
       [0.43927332, 0.        , 0.11342539, 0.443792  , 0.106734  ,
        0.47911487, 0.30826798, 0.62419018, 0.33153387, 0.45161988],
       [0.53882322, 0.11342539, 0.        , 0.48824063, 0.03443685,
        0.53893777, 0.37958215, 0.5279824 , 0.36416424, 0.37699833],
       [0.70303005, 0.443792  , 0.48824063, 0.        , 0.45430665,
        0.85963283, 0.69015855, 0.68223783, 0.75874747, 0.8642317 ],
       [0.54332408, 0.106734  , 0.03443685, 0.45430665, 0.        ,
        0.55843473, 0.39490823, 0.52001166, 0.38911706, 0.41035437],
       [0.25424385, 0.47911487, 0.53893777, 0.85963283, 0.55843473,
        0.        , 0.17402022, 1.05410507, 0.19641428, 0.55433985],
       [0.21522677, 0.30826798, 0.37958215, 0.69015855, 0.39490823,
        0.17402022, 0.        , 0.90489386, 0.13306878, 0.49090169],
       [1.06313451, 0.62419018, 0.5279824

Случайно расположить p элементов в 2D массив

In [50]:
n = 8
p = 7
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
Z



array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 1., 0.]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [51]:
a = np.array([1,2,3,4,5])
b = []
for i in a:
    b.append(i)
    b.append(0)
    b.append(0)
    b.append(0)
b = np.array(b)
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0])

Найти наиболее частое значение в массиве

In [52]:
from scipy import stats

a = np.array([[1, 1, 1, 2, 2, 2 ,2,5]])

m = stats.mode(a, axis = None)
print(m[0])

[2]



Найти n наибольших значений в массиве

In [53]:
x = np.arange(10)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 2
print (x[np.argsort(x)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[8 9]


## Pandas - изучение данных

In [56]:
import pandas as pd

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [58]:
food = pd.read_csv('pandas_data/en.openfoodfacts.org.products.tsv', sep='\t')

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Посмотреть первые 5 записей

In [59]:
food.head()

code                                                url  \
0   3087  http://world-en.openfoodfacts.org/product/0000...   
1   4530  http://world-en.openfoodfacts.org/product/0000...   
2   4559  http://world-en.openfoodfacts.org/product/0000...   
3  16087  http://world-en.openfoodfacts.org/product/0000...   
4  16094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity         ...         fruits-vegetables-nuts_100g  \
0          NaN      1kg         ...                                 NaN   
1          NaN      NaN         ...                                 NaN   
2          NaN      NaN         ...                                 NaN   
3          NaN      NaN         ...                                 NaN   
4          NaN      NaN         ...                                 NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [60]:
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [61]:
food.shape[1]

163

Напечатайте все названия столбцов

In [62]:
food.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Какое название у 105 столбца?

In [63]:
food.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [64]:
food['-glucose_100g'].head()
#float64

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: -glucose_100g, dtype: float64

Как проиндексирован набор данных?

In [65]:
food.index

RangeIndex(start=0, stop=356027, step=1)

Каково значение имени продукта в 19-м наблюдении?

In [68]:
food.loc[18,['product_name']][0]

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [71]:
chipo = pd.read_csv('pandas_data/chipotle.tsv', sep='\t')
chipo.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

Как много продуктов стоят более чем $10.00?

In [72]:
# обработка цены
chipo['item_price'] = chipo['item_price'].apply(lambda x: x.replace('$', '')).astype(float)
chipo['price_initial'] = chipo['item_price']/chipo['quantity']

In [74]:
chipo.loc[chipo['price_initial'] > 10.].shape[0]

1034

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [76]:
chipo.groupby(['item_name']).agg({'price_initial':'max'}).reset_index().head().\
                            rename(columns = {'price_initial':'item_price'})

item_name  item_price
0      6 Pack Soft Drink        6.49
1          Barbacoa Bowl       11.75
2       Barbacoa Burrito       11.75
3  Barbacoa Crispy Tacos       11.75
4    Barbacoa Salad Bowl       11.89

Отсортировать по имени предмета

In [79]:
chipo.sort_values('item_name').head()

order_id  quantity          item_name choice_description  item_price  \
3389      1360         2  6 Pack Soft Drink        [Diet Coke]       12.98   
341        148         1  6 Pack Soft Drink        [Diet Coke]        6.49   
1849       749         1  6 Pack Soft Drink             [Coke]        6.49   
1860       754         1  6 Pack Soft Drink        [Diet Coke]        6.49   
2713      1076         1  6 Pack Soft Drink             [Coke]        6.49   

      price_initial  
3389           6.49  
341            6.49  
1849           6.49  
1860           6.49  
2713           6.49

Сколько было заказано самого дорогого предмета?

In [80]:
most_exp_product = chipo.loc[chipo['price_initial'] == chipo['price_initial'].max()]['item_name'].unique()[0]
chipo.loc[chipo['item_name'] == most_exp_product]['quantity'].sum()

31

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [85]:
#chipo.loc[chipo['item_name'] == 'Veggie Salad Bowl'].shape[0]
chipo.loc[chipo['item_name'] == 'Veggie Salad Bowl']['quantity'].sum()

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [86]:
chipo.loc[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] >1)].shape[0]

20